# Generated by Django 4.0.4 on 2022-05-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_App', '0016_remove_history_order_remove_order_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='product_img',
            field=models.ImageField(default='', upload_to='product_images'),
        ),
    ]
