# Generated by Django 4.0.4 on 2022-05-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_App', '0019_remove_history_total_history_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='method',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tran_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
