# Generated by Django 4.0.4 on 2022-05-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_App', '0021_reservation_date_reservation_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='location',
        ),
        migrations.AddField(
            model_name='restaurent',
            name='location',
            field=models.CharField(default='', max_length=40),
        ),
    ]
