# Generated by Django 4.0.4 on 2022-05-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_App', '0022_remove_reservation_location_restaurent_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='order_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Restore', 'Restore')], default='Pending', max_length=40),
        ),
        migrations.AlterField(
            model_name='restaurent',
            name='location',
            field=models.CharField(default='', max_length=200),
        ),
    ]
